### PR TITLE
[RAD-3677 RAD-3678] Add support for add and remove event handlers in the new event detector scripts

### PR DESCRIPTION
**Pull request by jpuccinit**
### DESCRIPTION ###
 We are giving users the ability to create and edit event detectors and the ability to link/unlink event handlers.
 Add support for state & MULTISTATE  and BINARY detectors in the new Event Detector scripts
 ### JIRA ###
 https://radixiot.atlassian.net/browse/RAD-3677
 https://radixiot.atlassian.net/browse/RAD-3678

### CODE REVIEW

**Review by BenjaminPerez3PG — APPROVED** [review]
Nice Job.

**Comment by aasbra** [comment]
I added validation for the delimiter to the scripts, but I think we should increment the error counter if they try to link or unlink an event handler XID that is not a real event handler XID. What do you think?

**Comment by jpuccinit** [comment]
> I added validation for the delimiter to the scripts, but I think we should increment the error counter if they try to link or unlink an event handler XID that is not a real event handler XID. What do you think?

Is right, I put the failed++;

**Comment by jazdw** [comment]
@aasbra I will just caution that these scripts are very un-maintainable. There is no unit testing of these scripts and there is no way to automatically refactor them if we change the name of a method etc. Therefore they are very prone to breakage and there is no guarantee they will work with upcoming versions of Mango.

**Comment by aasbra** [comment]
> @aasbra I will just caution that these scripts are very un-maintainable. There is no unit testing of these scripts and there is no way to automatically refactor them if we change the name of a method etc. Therefore they are very prone to breakage and there is no guarantee they will work with upcoming versions of Mango.

@jazdw Understood. Would it be a good idea to add a reference in the script comments indicating which version of Mango was used when creating/testing the scripts? This might help make users aware of any compatibility issues if they upgrade their Mango install.

**Comment by jazdw** [comment]
@aasbra definitely not a bad idea.

**Pull request closed without merging**
